#!/usr/bin/env ruby
require 'io/console'
require './lib/alba_habla'

# Reads keypresses from the user including 2 and 3 escape character sequences.
# https://gist.github.com/acook/4190379
def read_char
  STDIN.echo = true
  STDIN.raw!

  input = STDIN.getc.chr
  if input == "\e" then
    input << STDIN.read_nonblock(3) rescue nil
    input << STDIN.read_nonblock(2) rescue nil
  end
ensure
  STDIN.echo = true
  STDIN.cooked!

  return input
end

command = nil

ah = AlbaHabla.new(File.expand_path(File.dirname(__FILE__)) + '/books/')

command_history = []

while command != 'bye'
  print "What shall I say? "
  # puts ah.prompt
  # char = read_char
  # case char
  # when "\e[A"
  #   puts "UP ARROW"
  # else
    command = gets.chomp
    command_history.push command
    ah.process_command(command)
  # end
end

puts "COMMAND HISTORY"
command_history.each{ |h| puts h }
